services:
  training:
    build: .
    volumes:
      - ./results:/app/results
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./results:/app/results
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/app

